version: '3.8'

services:
  api:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: spyTroth
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres

  postgres:
    env_file:
      - ../.env
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spyTroth
    volumes:
      - docker_pgdata:/var/lib/postgresql/data

volumes:
  docker_pgdata:
